### PR TITLE
Add shoryuken to the dummy app

### PR DESCRIPTION
**Pull request by johncalvinyoung**
I'd like to add [shoryuken](https://github.com/phstc/shoryuken) support to the dummy app to support testing my additions to `opsworks_ruby`.

It should also merge to a branch called `shoryuken`, but I'm not sure how to do that in a PR when the branch doesn't exist yet.

### CODE REVIEW

**Comment by ajgon** [comment]
Please, open a PR against different branch than master. Dummy-app has different branches, to support different configuration setups.

**Comment by johncalvinyoung** [comment]
@ajgon Just getting back to this--realized I'd entirely missed that you'd replied. My bad.

I can't open the PR against the right branch, as I think it needs to be a new branch--`shoryuken` preferably? It's an alternate job worker provider, like `resque` or `sidekiq`--this is a clone of the default rails/sidekiq build but with `shoryuken` subbed for sidekiq. I've got a fork of the opsworks-ruby that adds support for it, that I can push a PR for once this exists on your dummy-app repo.

**Comment by ajgon** [comment]
@johncalvinyoung Ah yes, that may be a case. I created a new branch from `master`: `shoryuken` which you can use as a PR base.

**Comment by johncalvinyoung** [comment]
@ajgon Updated the PR to point to the right base, and pull in the latest version of the gem

**Pull request merged**
